export  const REGISTER_SUCCESS="REGITER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export  const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export  const LOAD_PRODUCT_SUCCESS="LOAD_PRODUCT_SUCCESS"
export const LOAD_PRODUCT_FAIL = "LOAD_PRODUCT_FAIL"

export  const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export  const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export  const ADD_PANIER_SUCCESS="ADD_PANIER_SUCCESS"
export const ADD_PANIER_FAIL = "ADD_PANIER_FAIL"
export  const GET_PANIER_SUCCESS="GET_PANIER_SUCCESS"
export const GET_PANIER_FAIL = "GET_PANIER_FAIL"
export const DECONECT ='DECONECT'
export const UPDATE_PANIER_SUCESS = "UPDATE_PANIER_SUCESS"
export const UPDATE_PANIER_FAIL="UPDATE_PANIER_FAIL"
export const DELETE_PRODUCT_SUCESS = "DELETE_PRODUCT_SUCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"
